- name: Create Azure VM
  hosts: localhost
  connection: local

  vars:
    myResourceGroup: ansible
    myVnet: kubernetes-node-vnet
    mySubnet: kubernetes-node-subnet
    myPublicIP: kubernetes-node-publicip
    myNIC: kubernetes-node-nic
    myNetworkSecurityGroup: kubernetes-node-nsg
    myVM: kubernetes-node
    mySSHkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnlT/btLqT7/v0poIda7XqnIOi+0SGOlBbfuJfT7JY2KY3JkC4nbbxT8GzrXnEAV8LnZgtha17IVOiSxPQHynYWjc1YrWSeIRHXcnIuUq5HI+f16NhsQ3m/MFKMoVMvTx8weGp/Jn8H9cxpiUsIzVl4+3pmug7k9xoo1BRN3vOgz7rYfjLjPL1Hx7E/pAVABQlhY3AwagcP9u7EQdkzL2H7QmEpPT0rGLuDl543yHGYnTc84zKB8AUN46S2315X5/9ZSxyfbFCkKamcohNma/ikgjFz9eoMeXw1oJ4uriLOPr+TVUMmV0qsn5rEagpeBmjW9PQuVR0Cn2G478VIKPp master@master

  tasks:

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ myResourceGroup }}"
      name: "{{  myVnet }}"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ myResourceGroup }}"
      name: "{{ mySubnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ myVnet }}"

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ myResourceGroup }}"
      allocation_method: Static
      name: "{{ myPublicIP }}"
    register: output_ip_address

  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ myResourceGroup}}"
      name: "{{ myNetworkSecurityGroup }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound

        - name: ServerJS
          protocol: Tcp
          destination_port_range: 8080
          access: Allow
          priority: 1002
          direction: Inbound

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ myResourceGroup }}"
      name: "{{ myNIC }}"
      virtual_network: "{{ myVnet }}"
      subnet: "{{ mySubnet }}"
      public_ip_name: "{{ myPublicIP }}"
      security_group: "{{ myNetworkSecurityGroup }}"

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ myResourceGroup }}"
      name: "{{ myVM }}"
      vm_size: Standard_D2_v3
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ mySSHkey }}"
      network_interfaces: "{{ myNIC }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '18.04-LTS'
        version: latest

  - name: Print Public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."